#!/bin/bash

plist_path=~/Library/Preferences/com.reincubate.macos.cam.plist
last_id="$(plutil -extract LastSelectedDeviceID raw -o - $plist_path)"
key="PeerSettings_$last_id"

prior_settings=$(plutil -extract $key raw -o - $plist_path | base64 -d)
echo "Prior settings:"
echo "- backgroundBlurriness: $(echo $prior_settings | jq '.postProcessingSettings.portraitConfig.backgroundBlurriness')"
echo "- backgroundMode: $(echo $prior_settings | jq '.backgroundMode')"

echo "Updating backgroundBlurriness and backgroundMode..."
updated_settings=$(echo $prior_settings | jq '.postProcessingSettings.portraitConfig.backgroundBlurriness = 0 | .backgroundMode = "off"')
echo "Updated settings:"
echo "- backgroundBlurriness: $(echo $updated_settings | jq '.postProcessingSettings.portraitConfig.backgroundBlurriness')"
echo "- backgroundMode: $(echo $updated_settings | jq '.backgroundMode')"

plutil -replace $key -data $(echo $updated_settings | base64) $plist_path
